version: '2.1'

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  bundler-data:
    driver: local

services:
  db:
    hostname: db
    image: postgres:9.5.6-alpine
    volumes:
      - ./db/dumps:/db/dumps
      - ./tmp:/tmp
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1x2y3z4u

  redis:
    hostname: redis
    image: redis:3.2.4-alpine
    volumes:
      - redis-data:/var/lib/redis
    command: redis-server --appendonly yes

  base: &base
    hostname: base
    image: zrpaplicacoes/docker-in-rails:latest
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/home/app/web
      - bundler-data:/usr/local/bundle
    environment: &env
      DATABASE_URL: postgres://postgres:1x2y3z4u@db:5432/docker_in_rails_development
      REDIS_URL: redis://redis:6379
      RACK_ENV: development
      RAILS_ENV: development
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  app:
    <<: *base
    environment: *env
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    ports: ['80:3000']

  sidekiq:
    <<: *base
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment: *env

  shoryuken:
    <<: *base
    command: bundle exec shoryuken --rails -C config/shoryuken.yml
    environment: *env

  bundler:
    <<: *base
    command: bundle install -j4 --retry 3
    links: []
    environment: *env

  guard:
    <<: *base
    command: bundle exec guard start --no-bundler-warning --no-interactions
    environment:
      <<: *env
      DATABASE_URL: postgres://postgres:1x2y3z4u@db:5432/docker_in_rails_test
      RACK_ENV: test
      RAILS_ENV: test

  spec:
    <<: *base
    command:  bundle exec spec
    environment:
      <<: *env
      DATABASE_URL: postgres://postgres:1x2y3z4u@db.local:5432/docker_in_rails_test
      RACK_ENV: test
      RAILS_ENV: test
